CANDY = [
    "3 Musketeers",
    "Airheads",
    "Almond Joy",
    "Baby Ruth",
    "Butterfinger",
    "Candy Corn",
    "Dove",
    "Dum Dums",
    "Hershey Kiss",
    "Junior Mint",
    "KitKat",
    "M&M",
    "Peanut M&M",
    "Milk Duds",
    "MilkyWay",
    "Crunch",
    "PayDay",
    "Reece's Peanut Butter Cup",
    "Reece's Pieces",
    "Skittles",
    "Snickers",
    "Tootsie Roll",
    "Starburst",
    "Twix",
    "Whoppers",
    "York Peppermint Pattie"
]
